---
  language: "node_js"
  os: "linux"
  jobs: 
    include: 
      - 
        stage: "Release"
        name: "Releasing"
        node_js: "lts/*"
        deploy: 
          provider: "script"
          skip_cleanup: true
          script: "npx semantic-release"


# language: node_js
# os: linux

# node_js:
#   - 12.3.1

# jobs:
#   include:
#     # Define the release stage that runs semantic-release
#     - stage: release
#       name: "Releasing"
#       node_js: lts/*
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script: npx semantic-release
