---
language: "node_js"
os: "linux"
jobs:
  include:
    - stage: "Release"
      name: "Releasing"
      node_js: "lts/*"
      deploy:
        provider: "script"
        skip_cleanup: true
        script: "npx semantic-release"
